<?php
/**
 * @package     Epicom_MHub
 * @copyright   Copyright (c) 2020 Gamuza Technologies (http://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */
?>

<?php $this->setPriceDataObject ($this->getSource ()); ?>

<?php if ((float) $this->getSource ()->getFeeAmount ()): ?>
    <tr>
        <td class="label"><?php echo Mage::helper ('mhub')->__('Fee') ?></td>
        <td>
            <?php echo $this->displayPrices ($this->getSource ()->getBaseFeeAmount (), $this->getSource ()->getFeeAmount ()); ?>
        </td>
    </tr>
<?php endif; ?>

