<?php
/**
 * @package     Epicom_MHub
 * @copyright   Copyright (c) 2020 Gamuza Technologies (http://www.gamuza.com.br/)
 * @author      Eneias Ramos de Melo <eneias@gamuza.com.br>
 */
?>

<?php if ($this->getSource () instanceof Mage_Sales_Model_Order): ?>
    <?php if ((float) $this->getSource ()->getDiscountAmountRefunded () > 0): ?>
        <tr>
            <td class="label"><strong><?php echo Mage::helper ('mhub')->__('Discount refunded to customer') ?></strong></td>
            <td><strong><?php echo $this->getSource ()->getDiscountAmountRefunded (); ?></strong></td>
        </tr>
    <?php endif; ?>
<?php else: ?>
    <?php if ((float) $this->getSource ()->getDiscountAmount ()): ?>
        <tr>
            <td class="label"><strong><?php echo Mage::helper ('mhub')->__('Discount Refunded') ?></strong></td>
            <td><strong><?php echo $this->getSource ()->getDiscountAmount (); ?></strong></td>
        </tr>
    <?php endif;  ?>
<?php endif; ?>

